// CREDITS.md, generated from the manifest.
//
//   bun run assets:credits           # write it
//   bun run assets:credits --check   # fail if it is out of date (what the suite runs)
//
// Generated rather than hand-kept because attribution is a LICENCE OBLIGATION
// for anything under CC-BY, and a hand-kept list is one someone forgets to
// update on the day they add the asset - which is a licence violation that looks
// exactly like nothing at all. The manifest is the thing you cannot avoid
// editing to add a prop, so the credits are derived from it and checked, and an
// uncredited asset cannot pass the suite.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  HDRI_ASSETS,
  MESH_ASSETS,
  RAW_ASSETS,
  TEXTURE_ASSETS,
  textureMaps,
} from "../src/render3d/assets";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
export const CREDITS_PATH = join(ROOT, "CREDITS.md");

export function renderCredits(): string {
  const lines = [
    "# Credits",
    "",
    "Generated by `bun run assets:credits` from `MESH_ASSETS`, `TEXTURE_ASSETS`,",
    "`HDRI_ASSETS` and `RAW_ASSETS` in `src/render3d/assets.ts`. Do not edit by hand - add the",
    "asset to its manifest and regenerate, which is what `cli assets` checks.",
    "",
    "## 3D models",
    "",
  ];
  const keys = Object.keys(MESH_ASSETS).sort();
  if (keys.length === 0) {
    lines.push("_None yet._", "");
  } else {
    for (const key of keys) {
      const a = MESH_ASSETS[key]!;
      lines.push(`- **${key}** - "${a.author}", [source](${a.source}), ${a.license}`);
    }
    lines.push("");
  }
  lines.push("## Surface textures", "");
  const textures = Object.keys(TEXTURE_ASSETS).sort();
  if (textures.length === 0) {
    lines.push("_None authored; every surface is generated (see below)._", "");
  } else {
    for (const key of textures) {
      const a = TEXTURE_ASSETS[key]!;
      const maps = textureMaps(a).length;
      lines.push(
        `- **${key}** (${maps} map${maps === 1 ? "" : "s"}) - "${a.author}", [source](${a.source}), ${a.license}`,
      );
    }
    lines.push("");
  }
  lines.push("## Environment maps", "");
  const hdris = Object.keys(HDRI_ASSETS).sort();
  if (hdris.length === 0) {
    lines.push("_None yet; every level is lit by the generated sky._", "");
  } else {
    for (const key of hdris) {
      const a = HDRI_ASSETS[key]!;
      lines.push(
        `- **${key}** - "${a.author}", [source](${a.source.split(" ")[0]!}), ${a.license}`,
      );
    }
    lines.push("");
  }
  lines.push("## Raw maps", "");
  const raws = Object.keys(RAW_ASSETS).sort();
  if (raws.length === 0) {
    lines.push("_None yet._", "");
  } else {
    for (const key of raws) {
      const a = RAW_ASSETS[key]!;
      // A source that is a path in this repo is not a URL, and a credits line
      // pointing a browser at it would 404.
      const src = a.source.startsWith("http") ? `[source](${a.source.split(" ")[0]!})` : a.source;
      lines.push(`- **${key}** - "${a.author}", ${src}, ${a.license}`);
    }
    lines.push("");
  }
  // Everything else the game is made of, so this file is a complete answer to
  // "what is in here that someone else made" rather than only the binaries.
  lines.push(
    "## Everything else",
    "",
    "Every surface with no entry above is generated procedurally in",
    "`src/render3d/assets.ts` and is not derived from any third-party asset. The",
    "physics, rendering and tooling are original, ported from a C#/Godot prototype",
    "in this project's own history.",
    "",
  );
  return lines.join("\n");
}

if (import.meta.main) {
  const want = renderCredits();
  if (process.argv.includes("--check")) {
    const have = existsSync(CREDITS_PATH) ? readFileSync(CREDITS_PATH, "utf8") : "";
    if (have !== want) {
      console.error("[credits] CREDITS.md is out of date - run `bun run assets:credits`");
      process.exit(1);
    }
    console.log("[credits] up to date");
  } else {
    writeFileSync(CREDITS_PATH, want);
    console.log(`[credits] wrote ${CREDITS_PATH}`);
  }
}
