// CREDITS.md, generated from the manifest.
//
//   bun run assets:credits           # write it
//   bun run assets:credits --check   # fail if it is out of date (what the suite runs)
//
// Generated rather than hand-kept because attribution is a LICENCE OBLIGATION
// for anything under CC-BY, and a hand-kept list is one someone forgets to
// update on the day they add the asset - which is a licence violation that looks
// exactly like nothing at all. The manifest is the thing you cannot avoid
// editing to add a prop, so the credits are derived from it and checked, and an
// uncredited asset cannot pass the suite.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { MESH_ASSETS } from "../src/render3d/assets";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
export const CREDITS_PATH = join(ROOT, "CREDITS.md");

export function renderCredits(): string {
  const lines = [
    "# Credits",
    "",
    "Generated by `bun run assets:credits` from `MESH_ASSETS` in",
    "`src/render3d/assets.ts`. Do not edit by hand - add the asset to the manifest",
    "and regenerate, which is what `cli assets` checks.",
    "",
    "## 3D models",
    "",
  ];
  const keys = Object.keys(MESH_ASSETS).sort();
  if (keys.length === 0) {
    lines.push("_None yet._", "");
  } else {
    for (const key of keys) {
      const a = MESH_ASSETS[key]!;
      lines.push(`- **${key}** - "${a.author}", [source](${a.source}), ${a.license}`);
    }
    lines.push("");
  }
  // Everything else the game is made of, so this file is a complete answer to
  // "what is in here that someone else made" rather than only the binaries.
  lines.push(
    "## Everything else",
    "",
    "Surface textures are generated procedurally in `src/render3d/assets.ts` and are",
    "not derived from any third-party asset. The physics, rendering and tooling are",
    "original, ported from a C#/Godot prototype in this project's own history.",
    "",
  );
  return lines.join("\n");
}

if (import.meta.main) {
  const want = renderCredits();
  if (process.argv.includes("--check")) {
    const have = existsSync(CREDITS_PATH) ? readFileSync(CREDITS_PATH, "utf8") : "";
    if (have !== want) {
      console.error("[credits] CREDITS.md is out of date - run `bun run assets:credits`");
      process.exit(1);
    }
    console.log("[credits] up to date");
  } else {
    writeFileSync(CREDITS_PATH, want);
    console.log(`[credits] wrote ${CREDITS_PATH}`);
  }
}
