schema_version = "1.0.0"

id = "ivy"
version = "0.2.0"
name = "Ivy"
tagline = "Paint carpets of flat ivy leaves and place hanging vines"
maintainer = "Tristan Bray"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

[build]
paths_exclude_pattern = ["__pycache__/", "test_*.py"]
