// The facts a generation recorded about its own output, read off disk. Node
// only (the dev server, `vite.config.ts`'s preload list, bun tools): it imports
// `fs`, which is why it is not in `generated.ts`, which the browser loads.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { GeneratorKind, ParamValues } from "../level/generatorParams";
import { GENERATED_META_FILE, generatedDir, parseGeneratedKey, type GeneratorInput } from "./generated";

// What the generator service writes beside every `mesh.glb` (see
// plans/visuals-workspace.md, "The generator service").
export interface GeneratedMeta {
  key: string;
  kind: GeneratorKind;
  version: number;
  params: ParamValues;
  input: GeneratorInput;
  bytes: number; // of mesh.glb
  triangles: number;
  generatedAt: string; // ISO 8601
  blender: string; // the Blender version that built it
}

// `public/`, found from this file rather than from the working directory, so a
// caller run from anywhere reads the same tree. (Vite bundles its config with
// `import.meta.url` rewritten to this file's own URL, so the preload list gets
// the same answer.)
const PUBLIC_DIR = fileURLToPath(new URL("../../public", import.meta.url));

// A key's recorded facts, or null when the key is not a generated one or its
// `meta.json` is missing or unreadable (never generated on this machine, or
// generated by a service that crashed before writing it). `publicDir` is for
// tests.
export function generatedMeta(key: string, publicDir: string = PUBLIC_DIR): GeneratedMeta | null {
  const parsed = parseGeneratedKey(key);
  if (!parsed) return null;
  try {
    const text = readFileSync(`${publicDir}${generatedDir(parsed.kind, parsed.hash)}/${GENERATED_META_FILE}`, "utf8");
    return JSON.parse(text) as GeneratedMeta;
  } catch {
    return null;
  }
}
